// Generated by `pnpm --filter @edge-matte/worker run cf-typegen` — commit updates when bindings change.
interface Env {
  ASSETS: Fetcher;
  IMAGES: ImagesBinding;
  IMAGES_BUCKET: R2Bucket;
  APP_ORIGIN: string;
}
