name: Security scan

on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  security:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.ref != 'changeset-release/main' }}
    uses: webpresso/github-actions/.github/workflows/webpresso-security.yml@5cd210dadf5cd0c04ccfaf3e10025efd7dbd6439
    with:
      install_command: vp install --frozen-lockfile
      security_command: vp exec secretlint "**/*"
      runner: ubuntu-latest
